site_name: Web Hacking Black Belt Edition

theme:
  name: material
  features:
    - content.code.copy

  palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

favicon: assets/favicon.png
icon:
  logo: logo

nav:
  - Welcome Pack:
    - Welcome: 'WELCOME.md'